'use strict';

export default {
    SLIDER_INIT: 'SLIDER_INIT',
    EVERYOPUS_INIT: 'EVERYOPUS_INIT',
    EVERYOPUS_UPDATE_CLICK_STATUS: 'EVERYOPUS_UPDATE_CLICK_STATUS',
    ARTIST_INIT: 'ARTIST_INIT',
    TEACHER_INIT: 'TEACHER_INIT',
    FRIEND_UPDATE_INIT: 'FRIEND_UPDATE_INIT',
    FRIEND_UPDATE_ADD: 'FRIEND_UPDATE_ADD',
    LAZYLOAD_INIT: 'LAZYLOAD_INIT',
    
};